### ISSUE TITLE
Grid gallery to Telegram Album

### ISSUE THREAD

**Issue by s3wall** [Recursing/MySubredditsBot#1]
Currently links to gallery post seems to be broken

**Comment by s3wall** [comment]
Update: Those links (gallery posts) are broken in case of redirect to old.reddit.com,

Example of gallery post are listed [here](https://old.reddit.com/r/help/comments/i3n09t/image_galleries_do_not_show_up_on_old_reddit/), other mention to this problem [here](https://old.reddit.com/r/help/comments/oxiuw7/gallery_links_dont_work_on_old_reddit/) .

Recap:
### on a browser:
input:  https://old.reddit.com/gallery/i34dox
output : page not found

### on [slide (android app)](https://f-droid.org/en/packages/me.ccrama.redditslide/)
input:  https://www.reddit.com/gallery/i34dox
output: crash

expected output: viewing the gallery somehow even on slide or old.reddit.com

**Comment by Recursing** [comment]
Should be fixed with https://github.com/Recursing/MySubredditsBot/commit/608834d0230c97551866e3098952c8a7f42fab1d, thanks!
